# Generated by Django 4.2.8 on 2023-12-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material_used',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='product',
            name='products_infomation',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
