# Generated by Django 4.2.8 on 2023-12-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_clas_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='clas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
